# > 浦大喜奔 - SPDBCCC
^https?:\/\/image\.spdbccc\.com\.cn\/group\d\/.*\.JPG$ url script-response-body https://raw.githubusercontent.com/Ezrea7/R-Store/main/Res/Scripts/AntiAd/spdbccc.js

hostname = image.spdbccc.com.cn