# > 皮皮虾 - PPX
^https?:\/\/.+\.pipix\.com\/bds\/feed\/channel_list\/ url script-response-body https://raw.githubusercontent.com/Ezrea7/R-Store/main/Res/Scripts/AntiAd/ppx.js
^https?:\/\/.+\.pipix\.com\/bds\/user\/check_in\/ url script-response-body https://raw.githubusercontent.com/Ezrea7/R-Store/main/Res/Scripts/AntiAd/ppx.js

hostname = *.pipix.com