#!name=SearchEngine
#!homepage=https://github.com/Ezrea7/R-Store
#!raw-url=https://raw.githubusercontent.com/Ezrea7/R-Store/main/Rule/QuanX/Redirect/SearchEngine.conf
#!tg-group=https://t.me/lanjieguanggao
#!date=2024-11-27 20:24:00
#!---------------------------------------------------------------------------------------------------------------
#>>>>>>>>>>>>>>>>>>>>>>>翻译
# yd xxx (有道词典)
^https?:\/\/duckduckgo\.com\/\?q=yd\+([^&]+).+ url 302 https://dict.youdao.com/search?q=$1
# tc xxx (Google 译至中)
^https?:\/\/duckduckgo\.com\/\?q=tc\+([^&]+).+ url 302 https://translate.google.com/#view=home&op=translate&sl=auto&tl=zh-CN&text=$1
# te xxx (Google 译至英)
^https?:\/\/duckduckgo\.com\/\?q=te\+([^&]+).+ url 302 https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=$1
# tj xxx (Google 译至日)
^https?:\/\/duckduckgo\.com\/\?q=tj\+([^&]+).+ url 302 https://translate.google.com/#view=home&op=translate&sl=auto&tl=ja&text=$1

#>>>>>>>>>>>>>>>>>>>>>>>社区
# db xxx (豆瓣)
^https?:\/\/duckduckgo\.com\/\?q=db\+([^&]+).+ url 302 https://m.douban.com/search?query=$1
# zh xxx (知乎)
^https?:\/\/duckduckgo\.com\/\?q=zh\+([^&]+).+ url 302 http://www.zhihu.com/search?q=$1
# gh xxx (GitHub)
^https?:\/\/duckduckgo\.com\/\?q=gh\+([^&]+).+ url 302 https://github.com/search?q=$1
# v2 xxx (v2ex)
^https?:\/\/duckduckgo\.com\/\?q=v2\+([^&]+).+ url 302 https://www.google.com/search?q=site:v2ex.com/t $1
# ssp xxx (sspai)
^https?:\/\/duckduckgo\.com\/\?q=ssp\+([^&]+).+ url 302 https://sspai.com/search/post/$1

#>>>>>>>>>>>>>>>>>>>>>>>视频
# yt xxx (YouTube)
^https?:\/\/duckduckgo\.com\/\?q=yt\+([^&]+).+ url 302 https://www.youtube.com/results?search_query=$1
# bl xxx (哔哩哔哩)
^https?:\/\/duckduckgo\.com\/\?q=bl\+([^&]+).+ url 302 https://m.bilibili.com/search?keyword=$1

#>>>>>>>>>>>>>>>>>>>>>>>搜索
# bd xxx (百度)
^https?:\/\/duckduckgo\.com\/\?q=bd\+([^&]+).+ url 302 https://www.baidu.com/s?wd=$1
# wk xxx (维基)
^https?:\/\/duckduckgo\.com\/\?q=wk\+([^&]+).+ url 302 https://zh.wikipedia.org/wiki/$1
# yh xxx (油猴)
^https?:\/\/duckduckgo\.com\/\?q=yh\+([^&]+).+ url 302 https://greasyfork.org/zh-CN/scripts?q=$1
# gi xxx (Google图片)
^https?:\/\/duckduckgo\.com\/\?q=gi\+([^&]+).+ url 302 https://www.google.com/search?&tbm=isch&q=$1
# by xxx (必应)
^https?:\/\/duckduckgo\.com\/\?q=by\+([^&]+).+ url 302 https://www.bing.com/search?q=$1
# qm xxx (七麦)
^https?:\/\/duckduckgo\.com\/\?q=qm\+([^&]+).+ url 302 https://www.qimai.cn/search/index/search/$1
# dd xxx (devdocs)
^https?:\/\/duckduckgo\.com\/\?q=dd\+([^&]+).+ url 302 https://devdocs.io/#q=$1

hostname = duckduckgo.com